import React from 'react'
import Navbar from '../Navbar'
import bear from '../assets/bear.png';

const Home = () => {
  return (
    <>
      <Navbar />
      <div className='bg-gradient-to-r from-blue-50 via-indigo-50 to-blue-50 bg-cover bg-center w-full h-full w-full p-6'>
        
      <div className="grid grid-cols-3 gap-4 relative place-content-center border-2 h-full ">
        <div className="border-2 border-black ...">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus iure ab voluptates et earum alias sit quasi odit labore animi ducimus cum ea unde, veniam officia atque dolore! Animi nulla tempora sapiente ipsa, iste, alias quis unde ullam optio amet, quos eius voluptas placeat eum laborum sunt. Molestiae doloremque dignissimos nihil et placeat dicta. Error sit, ad molestiae perferendis nesciunt voluptas pariatur sequi corrupti neque. Harum asperiores ullam perferendis fugiat itaque voluptatum suscipit tempore, molestias incidunt ipsam quod? Adipisci ex dicta placeat quae blanditiis corporis rerum nulla explicabo pariatur, sit nisi, laudantium sed porro tenetur tempora fugiat ratione quo est! Commodi laudantium, accusantium rerum non minus laboriosam iste saepe libero, porro harum odit sint voluptatibus impedit. Laborum suscipit numquam consectetur voluptate tempore atque ratione. Veritatis labore id quisquam quo eligendi, itaque, adipisci a cum est, temporibus nam cumque! Exercitationem, eveniet dolores culpa ratione eos dolor omnis accusamus dolore maxime totam, velit voluptatem reiciendis adipisci harum explicabo in quibusdam fugit dolorem sequi earum esse natus! Impedit inventore debitis obcaecati commodi cumque in doloremque eos natus. Esse illum ipsum sit vel magnam, nostrum eaque repudiandae omnis beatae commodi quam fugit quo similique vitae alias officiis recusandae. Dignissimos dicta error sunt quam aliquam.</div>
        <div className="border-2 border-black ...">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus iure ab voluptates et earum alias sit quasi odit labore animi ducimus cum ea unde, veniam officia atque dolore! Animi nulla tempora sapiente ipsa, iste, alias quis unde ullam optio amet, quos eius voluptas placeat eum laborum sunt. Molestiae doloremque dignissimos nihil et placeat dicta. Error sit, ad molestiae perferendis nesciunt voluptas pariatur sequi corrupti neque. Harum asperiores ullam perferendis fugiat itaque voluptatum suscipit tempore, molestias incidunt ipsam quod? Adipisci ex dicta placeat quae blanditiis corporis rerum nulla explicabo pariatur, sit nisi, laudantium sed porro tenetur tempora fugiat ratione quo est! Commodi laudantium, accusantium rerum non minus laboriosam iste saepe libero, porro harum odit sint voluptatibus impedit. Laborum suscipit numquam consectetur voluptate tempore atque ratione. Veritatis labore id quisquam quo eligendi, itaque, adipisci a cum est, temporibus nam cumque! Exercitationem, eveniet dolores culpa ratione eos dolor omnis accusamus dolore maxime totam, velit voluptatem reiciendis adipisci harum explicabo in quibusdam fugit dolorem sequi earum esse natus! Impedit inventore debitis obcaecati commodi cumque in doloremque eos natus. Esse illum ipsum sit vel magnam, nostrum eaque repudiandae omnis beatae commodi quam fugit quo similique vitae alias officiis recusandae. Dignissimos dicta error sunt quam aliquam.</div>
        <div className="border-2 border-black ...">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus iure ab voluptates et earum alias sit quasi odit labore animi ducimus cum ea unde, veniam officia atque dolore! Animi nulla tempora sapiente ipsa, iste, alias quis unde ullam optio amet, quos eius voluptas placeat eum laborum sunt. Molestiae doloremque dignissimos nihil et placeat dicta. Error sit, ad molestiae perferendis nesciunt voluptas pariatur sequi corrupti neque. Harum asperiores ullam perferendis fugiat itaque voluptatum suscipit tempore, molestias incidunt ipsam quod? Adipisci ex dicta placeat quae blanditiis corporis rerum nulla explicabo pariatur, sit nisi, laudantium sed porro tenetur tempora fugiat ratione quo est! Commodi laudantium, accusantium rerum non minus laboriosam iste saepe libero, porro harum odit sint voluptatibus impedit. Laborum suscipit numquam consectetur voluptate tempore atque ratione. Veritatis labore id quisquam quo eligendi, itaque, adipisci a cum est, temporibus nam cumque! Exercitationem, eveniet dolores culpa ratione eos dolor omnis accusamus dolore maxime totam, velit voluptatem reiciendis adipisci harum explicabo in quibusdam fugit dolorem sequi earum esse natus! Impedit inventore debitis obcaecati commodi cumque in doloremque eos natus. Esse illum ipsum sit vel magnam, nostrum eaque repudiandae omnis beatae commodi quam fugit quo similique vitae alias officiis recusandae. Dignissimos dicta error sunt quam aliquam.</div>
        <div className="border-2 border-black col-span-2 ...">Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque quam, earum iusto vitae repellat molestias est eos unde aliquam debitis ullam laudantium quo esse deserunt nihil delectus suscipit, totam soluta sapiente ut fuga rem facilis doloribus error! Voluptatibus, delectus ipsam rerum fuga non quibusdam commodi corporis tenetur repellat vitae vel earum porro impedit accusamus provident nemo reiciendis sed quas quasi eaque doloribus enim dolorum magni? Quidem placeat rem repudiandae et tempore distinctio deserunt nostrum velit nisi eos animi, voluptas porro pariatur. Ab tempore possimus odio ducimus, illum, nihil, perferendis veniam incidunt dolorum dolore commodi. Modi at nostrum aut harum, deserunt labore dignissimos officia cumque fuga sequi magni. Nesciunt accusamus provident blanditiis, voluptatibus illum laudantium porro aut modi facilis repellat, exercitationem non a rerum voluptas distinctio cupiditate dignissimos? Optio asperiores odit corrupti sint iste, error similique deserunt quasi omnis doloremque quibusdam labore eos aliquid nobis ullam laudantium vel neque, quidem, voluptatibus nesciunt ducimus incidunt temporibus. Assumenda vero architecto ea reiciendis enim! Debitis, magnam voluptates qui dolorum blanditiis eos iure provident quis. Alias iure quo at, consectetur officia magnam ipsa possimus! Amet, sed vel. Qui deleniti sint repellendus ipsum harum voluptatibus perspiciatis quibusdam iste, amet suscipit minus voluptatem at nostrum aperiam dignissimos!</div>
        <div className="border-2 border-black ..."><img src={bear} alt="" className='object-contain' /></div>
        <div className="border-2 border-black ...">Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque quam, earum iusto vitae repellat molestias est eos unde aliquam debitis ullam laudantium quo esse deserunt nihil delectus suscipit, totam soluta sapiente ut fuga rem facilis doloribus error! Voluptatibus, delectus ipsam rerum fuga non quibusdam commodi corporis tenetur repellat vitae vel earum porro impedit accusamus provident nemo reiciendis sed quas quasi eaque doloribus enim dolorum magni? Quidem placeat rem repudiandae et tempore distinctio deserunt nostrum velit nisi eos animi, voluptas porro pariatur. Ab tempore possimus odio ducimus, illum, nihil, perferendis veniam incidunt dolorum dolore commodi. Modi at nostrum aut harum, deserunt labore dignissimos officia cumque fuga sequi magni. Nesciunt accusamus provident blanditiis, voluptatibus illum laudantium porro aut modi facilis repellat, exercitationem non a rerum voluptas distinctio cupiditate dignissimos? Optio asperiores odit corrupti sint iste, error similique deserunt quasi omnis doloremque quibusdam labore eos aliquid nobis ullam laudantium vel neque, quidem, voluptatibus nesciunt ducimus incidunt temporibus. Assumenda vero architecto ea reiciendis enim! Debitis, magnam voluptates qui dolorum blanditiis eos iure provident quis. Alias iure quo at, consectetur officia magnam ipsa possimus! Amet, sed vel. Qui deleniti sint repellendus ipsum harum voluptatibus perspiciatis quibusdam iste, amet suscipit minus voluptatem at nostrum aperiam dignissimos!</div>
        <div className="border-2 border-black col-span-2 ...">Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque quam, earum iusto vitae repellat molestias est eos unde aliquam debitis ullam laudantium quo esse deserunt nihil delectus suscipit, totam soluta sapiente ut fuga rem facilis doloribus error! Voluptatibus, delectus ipsam rerum fuga non quibusdam commodi corporis tenetur repellat vitae vel earum porro impedit accusamus provident nemo reiciendis sed quas quasi eaque doloribus enim dolorum magni? Quidem placeat rem repudiandae et tempore distinctio deserunt nostrum velit nisi eos animi, voluptas porro pariatur. Ab tempore possimus odio ducimus, illum, nihil, perferendis veniam incidunt dolorum dolore commodi. Modi at nostrum aut harum, deserunt labore dignissimos officia cumque fuga sequi magni. Nesciunt accusamus provident blanditiis, voluptatibus illum laudantium porro aut modi facilis repellat, exercitationem non a rerum voluptas distinctio cupiditate dignissimos? Optio asperiores odit corrupti sint iste, error similique deserunt quasi omnis doloremque quibusdam labore eos aliquid nobis ullam laudantium vel neque, quidem, voluptatibus nesciunt ducimus incidunt temporibus. Assumenda vero architecto ea reiciendis enim! Debitis, magnam voluptates qui dolorum blanditiis eos iure provident quis. Alias iure quo at, consectetur officia magnam ipsa possimus! Amet, sed vel. Qui deleniti sint repellendus ipsum harum voluptatibus perspiciatis quibusdam iste, amet suscipit minus voluptatem at nostrum aperiam dignissimos!</div>
      </div>
        
      </div>
    </>
  )
}

export default Home